---
sidebar: sidebar 
permalink: concept-degraded-ha-pair.html 
keywords: storage takeover, storage giveback, degraded, degraded status, degraded state, ha pair, ha takeover, takeover, giveback 
summary: 'Quando un nodo in una coppia ha non è disponibile, l"altro nodo serve i dati per il partner per fornire un servizio dati continuo. Si tratta di un processo chiamato "Takeover dello storage". Diverse azioni non sono disponibili fino al completamento del giveback in storage.' 
---
= Azioni non disponibili durante il takeover
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando un nodo in una coppia ha non è disponibile, l'altro nodo serve i dati per il partner per fornire un servizio dati continuo. Si chiama _storage Takeover_. Diverse azioni non sono disponibili fino al completamento del giveback in storage.


TIP: Quando un nodo in una coppia ha non è disponibile, lo stato dell'ambiente di lavoro in BlueXP è _degradato_.

Le seguenti azioni non sono disponibili dall'acquisizione dello storage BlueXP:

* Registrazione del supporto
* Modifiche della licenza
* Modifiche all'istanza o al tipo di macchina virtuale
* La velocità di scrittura cambia
* Setup CIFS
* Modifica della posizione dei backup di configurazione
* Impostazione della password del cluster
* Gestione di dischi e aggregati (allocazione avanzata)


Queste azioni sono nuovamente disponibili al termine del giveback dello storage e quando lo stato dell'ambiente di lavoro torna alla normalità.
