---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage, tiering 
summary: 'È possibile attivare lo storage WORM (Write Once, Read Many) su un sistema Cloud Volumes ONTAP per conservare i file in forma non modificata per un periodo di conservazione specificato. Lo storage cloud WORM è basato sulla tecnologia SnapLock, il che significa che i file WORM sono protetti a livello di file.' 
---
= Storage WORM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile attivare lo storage WORM (Write Once, Read Many) su un sistema Cloud Volumes ONTAP per conservare i file in forma non modificata per un periodo di conservazione specificato. Lo storage cloud WORM è basato sulla tecnologia SnapLock, il che significa che i file WORM sono protetti a livello di file.



== Come funziona lo storage WORM

Una volta che un file è stato impegnato nello storage WORM, non può essere modificato, anche dopo la scadenza del periodo di conservazione. Un clock a prova di manomissione determina quando è trascorso il periodo di conservazione di un file WORM.

Una volta trascorso il periodo di conservazione, l'utente è responsabile dell'eliminazione dei file non più necessari.



== In carica

Il costo per lo storage WORM è orario, in base alla capacità di provisioning totale dei volumi WORM.

Disponibile solo per PAYGO o termini di impegno annuali, la licenza per WORM è acquistabile attraverso il mercato del Cloud Provider. WORM supporta modelli di licenza basati su nodo e su capacità.


NOTE: La licenza BYOL non è disponibile per lo storage WORM su Cloud Volumes ONTAP.

È necessario comprendere il seguente comportamento di ricarica con Cloud Volumes ONTAP 9.10.1 e versioni successive:

* A partire da ONTAP 9.10.1, i volumi WORM e i volumi non WORM possono esistere sullo stesso aggregato.
* Se si attiva WORM durante la creazione di un ambiente di lavoro Cloud Volumes ONTAP, ogni volume creato da BlueXP ha abilitato WORM. Tuttavia, è possibile utilizzare l'interfaccia utente di ONTAP o Gestore di sistema per creare volumi con WORM disattivato. Questi volumi non vengono addebitati al TASSO WORM.
* Se non si attiva WORM quando si crea un ambiente di lavoro, ogni volume creato da BlueXP ha DISATTIVATO WORM. Non viene addebitato IL TASSO WORM per tali volumi.


https://cloud.netapp.com/pricing["Scopri i prezzi dello storage WORM"^]



== Attivazione dello storage WORM

La modalità di attivazione dello storage WORM dipende dalla versione di Cloud Volumes ONTAP in uso.



=== Versione 9.10.1 e successive

A partire da Cloud Volumes ONTAP 9.10.1, è possibile attivare o disattivare WORM a livello di volume.

Quando si crea un nuovo ambiente di lavoro Cloud Volumes ONTAP, viene richiesto di attivare o disattivare lo storage WORM:

* Se si attiva lo storage WORM durante la creazione di un ambiente di lavoro, ogni volume creato da BlueXP ha abilitato WORM. Tuttavia, è possibile utilizzare System Manager o CLI per creare volumi con WORM disattivato.
* Se si disattiva lo storage WORM durante la creazione di un ambiente di lavoro, ogni volume creato da BlueXP, System Manager o CLI ha disattivato WORM. Se si desidera attivare WORM su un ambiente di lavoro Cloud Volumes ONTAP non abilitato durante la creazione, è necessario creare un ticket di supporto con il supporto NetApp per ricevere assistenza.


Con entrambe le opzioni, dovresti <<In carica,comprendere il funzionamento della ricarica>>.



=== Versione 9.10.0 e precedenti

È possibile attivare lo storage WORM su un sistema Cloud Volumes ONTAP quando si crea un nuovo ambiente di lavoro. Ogni volume creato da BlueXP ha abilitato WORM. Non è possibile disattivare lo storage WORM su singoli volumi.



== Commit dei file in WORM

È possibile utilizzare un'applicazione per il commit dei file in WORM su NFS o CIFS oppure utilizzare l'interfaccia utente di ONTAP per il commit automatico dei file in WORM. È inoltre possibile utilizzare un file .WORM appendibile per conservare i dati scritti in modo incrementale, ad esempio le informazioni di log.

Dopo aver attivato lo storage WORM su un sistema Cloud Volumes ONTAP, è necessario utilizzare l'interfaccia utente di ONTAP per la gestione dello storage WORM. Per istruzioni, fare riferimento a. http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["Documentazione ONTAP"^].



== Eliminazione dei file WORM

È possibile eliminare i file WORM durante il periodo di conservazione utilizzando la funzione di eliminazione con privilegi.

Per istruzioni, fare riferimento a. https://docs.netapp.com/us-en/ontap/snaplock/delete-worm-files-concept.html["Documentazione ONTAP"^]



== WORM e tiering dei dati

Quando si crea un nuovo sistema Cloud Volumes ONTAP 9.8 o versione successiva, è possibile abilitare contemporaneamente il tiering dei dati e lo storage WORM. L'abilitazione del tiering dei dati con lo storage WORM consente di eseguire il tiering dei dati in un archivio di oggetti nel cloud.

È necessario comprendere quanto segue sull'abilitazione del tiering dei dati e dello storage WORM:

* I dati a più livelli per lo storage a oggetti non includono la funzionalità WORM di ONTAP. Per garantire la funzionalità WORM end-to-end, è necessario impostare correttamente le autorizzazioni del bucket.
* I dati che vengono suddivisi in livelli per lo storage a oggetti non sono dotati della funzionalità WORM, il che significa che chiunque abbia accesso completo ai bucket e ai container può eliminare gli oggetti suddivisi in livelli da ONTAP.
* Il ripristino o il downgrade a Cloud Volumes ONTAP 9.8 viene bloccato dopo l'abilitazione DI WORM e tiering.




== Limitazioni

* Lo storage WORM in Cloud Volumes ONTAP opera sotto un modello "trusted storage Administrator". Mentre i file WORM sono protetti da modifiche o modifiche, i volumi possono essere cancellati da un amministratore del cluster anche se tali volumi contengono dati WORM non scaduti.
* Oltre al modello di amministratore dello storage fidato, lo storage WORM in Cloud Volumes ONTAP opera implicitamente anche sotto un modello di "amministratore del cloud fidato". Un amministratore del cloud potrebbe eliminare i dati WORM prima della data di scadenza rimuovendo o modificando lo storage cloud direttamente dal cloud provider.

