---
sidebar: sidebar 
permalink: concept-storage-management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode, BlueXP, cloud manager 
summary: BlueXP offre una gestione semplificata e avanzata dello storage Cloud Volumes ONTAP. 
---
= Gestione dello storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP offre una gestione semplificata e avanzata dello storage Cloud Volumes ONTAP.


CAUTION: Tutti i dischi e gli aggregati devono essere creati ed eliminati direttamente da BlueXP. Non eseguire queste azioni da un altro tool di gestione. In questo modo si può influire sulla stabilità del sistema, ostacolare la possibilità di aggiungere dischi in futuro e potenzialmente generare tariffe ridondanti per i provider di cloud.



== Provisioning dello storage

BlueXP semplifica il provisioning dello storage per Cloud Volumes ONTAP acquistando dischi e gestendo aggregati. È sufficiente creare volumi. Se lo si desidera, è possibile utilizzare un'opzione di allocazione avanzata per eseguire il provisioning degli aggregati.



=== Provisioning semplificato

Gli aggregati forniscono lo storage cloud ai volumi. BlueXP crea aggregati per l'utente al momento del lancio di un'istanza e del provisioning di volumi aggiuntivi.

Quando si crea un volume, BlueXP esegue una delle tre operazioni seguenti:

* Posiziona il volume su un aggregato esistente con spazio libero sufficiente.
* Il volume viene inserito in un aggregato esistente acquistando più dischi per tale aggregato.


ifdef::aws[]

+
Nel caso di un aggregato in AWS che supporta volumi elastici, BlueXP aumenta anche la dimensione dei dischi di un gruppo RAID. link:concept-aws-elastic-volumes.html["Scopri di più sul supporto per volumi elastici"].

endif::aws[]

* L'IT acquista dischi per un nuovo aggregato e colloca il volume su tale aggregato.


BlueXP determina dove posizionare un nuovo volume prendendo in considerazione diversi fattori: La dimensione massima di un aggregato, l'attivazione del thin provisioning e le soglie di spazio libero per gli aggregati.


TIP: L'amministratore dell'account può modificare le soglie di spazio libero dalla pagina *Impostazioni*.

ifdef::aws[]



==== Selezione delle dimensioni dei dischi per gli aggregati in AWS

Quando BlueXP crea nuovi aggregati per Cloud Volumes ONTAP in AWS, aumenta gradualmente la dimensione del disco in un aggregato, con l'aumentare del numero di aggregati nel sistema. BlueXP garantisce che sia possibile utilizzare la capacità massima del sistema prima che raggiunga il numero massimo di dischi dati consentito da AWS.

Ad esempio, BlueXP potrebbe scegliere le seguenti dimensioni dei dischi:

[cols="3*"]
|===
| Numero aggregato | Dimensioni del disco | Capacità aggregata massima 


| 1 | 500 GiB | 3 TiB 


| 4 | 1 TIB | 6 TIB 


| 6 | 2 TIB | 12 TiB 
|===

NOTE: Questo comportamento non si applica agli aggregati che supportano la funzionalità Amazon EBS Elastic Volumes. Gli aggregati con volumi elastici abilitati sono costituiti da uno o due gruppi RAID. Ogni gruppo RAID ha quattro dischi identici che hanno la stessa capacità. link:concept-aws-elastic-volumes.html["Scopri di più sul supporto per volumi elastici"].

È possibile scegliere autonomamente le dimensioni del disco utilizzando l'opzione Advanced allocation (allocazione avanzata).

endif::aws[]



=== Allocazione avanzata

Invece di consentire a BlueXP di gestire gli aggregati, puoi farlo da solo. link:task-create-aggregates.html["Dalla pagina *allocazione avanzata*"], è possibile creare nuovi aggregati che includono un numero specifico di dischi, aggiungere dischi a un aggregato esistente e creare volumi in aggregati specifici.



== Gestione della capacità

L'account Admin può scegliere se BlueXP notifica le decisioni relative alla capacità dello storage o se BlueXP gestisce automaticamente i requisiti di capacità.

Questo comportamento è determinato dalla _modalità di gestione della capacità_ di un connettore. La modalità di gestione della capacità influisce su tutti i sistemi Cloud Volumes ONTAP gestiti da tale connettore. Se si dispone di un altro connettore, è possibile configurarlo in modo diverso.



=== Gestione automatica della capacità

Per impostazione predefinita, Capacity Management Mode (modalità di gestione della capacità) è impostata su Automatic (automatica). In questa modalità, BlueXP acquista automaticamente nuovi dischi per le istanze di Cloud Volumes ONTAP quando è necessaria una maggiore capacità, elimina raccolte di dischi inutilizzate (aggregati), sposta i volumi tra aggregati quando necessario e tenta di eliminare i dischi guasti.

I seguenti esempi illustrano il funzionamento di questa modalità:

* Se un aggregato raggiunge la soglia di capacità e dispone di spazio per più dischi, BlueXP acquista automaticamente nuovi dischi per quell'aggregato in modo che i volumi possano continuare a crescere.
+
BlueXP verifica il rapporto di spazio libero ogni 15 minuti per determinare se è necessario acquistare dischi aggiuntivi.



ifdef::aws[]

+
Nel caso di un aggregato in AWS che supporta volumi elastici, BlueXP aumenta anche la dimensione dei dischi di un gruppo RAID. link:concept-aws-elastic-volumes.html["Scopri di più sul supporto per volumi elastici"].

endif::aws[]

* Se un aggregato raggiunge la soglia di capacità e non supporta dischi aggiuntivi, BlueXP sposta automaticamente un volume da tale aggregato a un aggregato con capacità disponibile o a un nuovo aggregato.
+
Se BlueXP crea un nuovo aggregato per il volume, sceglie una dimensione del disco che si adatta alle dimensioni del volume.

+
Si noti che lo spazio libero è ora disponibile sull'aggregato originale. I volumi esistenti o nuovi volumi possono utilizzare tale spazio. In questo scenario, non è possibile restituire lo spazio al cloud provder.

* Se un aggregato non contiene volumi per più di 12 ore, BlueXP lo elimina.




==== Gestione delle LUN con gestione automatica della capacità

La gestione automatica della capacità di BlueXP non si applica alle LUN. Quando BlueXP crea un LUN, disattiva la funzione di crescita automatica.



=== Gestione manuale della capacità

Se l'account Admin imposta la modalità di gestione della capacità su manuale, BlueXP visualizza i messaggi Action Required (azione richiesta) quando è necessario prendere decisioni in merito alla capacità. Gli stessi esempi descritti nella modalità automatica si applicano alla modalità manuale, ma spetta all'utente accettare le azioni.



=== Scopri di più

link:task-manage-capacity-settings.html["Scopri come modificare la modalità di gestione della capacità"].
