---
sidebar: sidebar 
permalink: concept-performance.html 
keywords: performance, technical report, TR, workload, cpu 
summary: Puoi esaminare i risultati delle performance per aiutarti a decidere quali carichi di lavoro sono appropriati per Cloud Volumes ONTAP. 
---
= Performance
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puoi esaminare i risultati delle performance per aiutarti a decidere quali carichi di lavoro sono appropriati per Cloud Volumes ONTAP.



== Report tecnici sulle performance

ifdef::aws[]

* Cloud Volumes ONTAP per AWS
+
link:https://www.netapp.com/pdf.html?item=/media/9088-tr4383pdf.pdf["Report tecnico di NetApp 4383: Caratterizzazione delle performance di Cloud Volumes ONTAP nei servizi Web Amazon con carichi di lavoro delle applicazioni"^]



endif::aws[]

ifdef::azure[]

* Cloud Volumes ONTAP per Microsoft Azure
+
link:https://www.netapp.com/pdf.html?item=/media/9089-tr-4671pdf.pdf["Report tecnico di NetApp 4671: Caratterizzazione delle performance di Cloud Volumes ONTAP in Azure con carichi di lavoro applicativi"^]



endif::azure[]

ifdef::gcp[]

* Cloud Volumes ONTAP per Google Cloud
+
link:https://www.netapp.com/pdf.html?item=/media/9090-tr4816pdf.pdf["Report tecnico NetApp 4816: Caratterizzazione delle performance di Cloud Volumes ONTAP per Google Cloud"^]



endif::gcp[]



== Performance della CPU

I nodi Cloud Volumes ONTAP risultano altamente utilizzati (oltre il 90%) dagli strumenti di monitoraggio del tuo cloud provider. Questo perché ONTAP riserva tutte le vCPU presentate alla macchina virtuale in modo che siano disponibili quando necessario.

Per ulteriori informazioni, consultare https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Monitoring_CPU_utilization_before_an_ONTAP_upgrade["Articolo della Knowledge base di NetApp su come monitorare l'utilizzo della CPU ONTAP utilizzando la CLI"^]
