---
sidebar: sidebar 
permalink: task-planning-your-config-gcp.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported machine types, supported virtual machines, supported vms, supported instances 
summary: Quando si implementa Cloud Volumes ONTAP, è possibile scegliere un sistema preconfigurato che soddisfi i requisiti del carico di lavoro oppure creare una configurazione personalizzata. Se si sceglie una configurazione personalizzata, è necessario comprendere le opzioni disponibili. 
---
= Pianificare la configurazione di Cloud Volumes ONTAP in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si implementa Cloud Volumes ONTAP in Google Cloud, è possibile scegliere un sistema preconfigurato che soddisfi i requisiti del carico di lavoro oppure creare una configurazione personalizzata. Se si sceglie una configurazione personalizzata, è necessario comprendere le opzioni disponibili.



== Scegliere una licenza Cloud Volumes ONTAP

Per Cloud Volumes ONTAP sono disponibili diverse opzioni di licenza. Ciascuna opzione consente di scegliere un modello di consumo che soddisfi le proprie esigenze.

* link:concept-licensing.html["Scopri le opzioni di licenza per Cloud Volumes ONTAP"]
* link:task-set-up-licensing-google.html["Scopri come impostare le licenze"]




== Scegliere una regione supportata

Cloud Volumes ONTAP è supportato nella maggior parte delle regioni di Google Cloud. https://cloud.netapp.com/cloud-volumes-global-regions["Visualizza l'elenco completo delle regioni supportate"^].



== Scegliere un tipo di computer supportato

Cloud Volumes ONTAP supporta diversi tipi di computer, a seconda del tipo di licenza scelto.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configurazioni supportate per Cloud Volumes ONTAP in GCP"^]



== Comprendere i limiti dello storage

Il limite di capacità raw per un sistema Cloud Volumes ONTAP è legato alla licenza. Ulteriori limiti influiscono sulle dimensioni degli aggregati e dei volumi. Durante la pianificazione della configurazione, è necessario conoscere questi limiti.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-gcp.html["Limiti di storage per Cloud Volumes ONTAP in GCP"^]



== Dimensionare il sistema in GCP

Il dimensionamento del sistema Cloud Volumes ONTAP può aiutarti a soddisfare i requisiti di performance e capacità. Quando si sceglie un tipo di macchina, un tipo di disco e una dimensione del disco, occorre tenere presente alcuni punti chiave:

Tipo di macchina:: Esaminare i tipi di computer supportati in http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["Note di rilascio di Cloud Volumes ONTAP"^] Quindi, esamina i dettagli di Google relativi a ciascun tipo di computer supportato. Abbina i requisiti di carico di lavoro al numero di vCPU e di memoria per il tipo di computer. Si noti che ogni core della CPU aumenta le performance di rete.
+
--
Per ulteriori informazioni, fare riferimento a quanto segue:

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Documentazione di Google Cloud: Tipi di computer standard N1"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Documentazione Google Cloud: Performance"^]


--
Tipo di disco GCP:: Quando crei volumi per Cloud Volumes ONTAP, devi scegliere lo storage cloud sottostante utilizzato da Cloud Volumes ONTAP per un disco. Il tipo di disco può essere uno dei seguenti:
+
--
* _Dischi persistenti SSD Zonal_: I dischi persistenti SSD sono ideali per i carichi di lavoro che richiedono elevati tassi di IOPS casuali.
* _Dischi persistenti bilanciati zonali_: Questi SSD bilanciano le performance e i costi fornendo IOPS per GB inferiori.
* _Dischi persistenti standard zonali_ : i dischi persistenti standard sono economici e possono gestire operazioni di lettura/scrittura sequenziali.
+
Per ulteriori informazioni, vedere https://cloud.google.com/compute/docs/disks/#pdspecs["Documentazione di Google Cloud: Dischi persistenti zonali (Standard e SSD)"^].



--
Dimensioni del disco GCP:: Quando si implementa un sistema Cloud Volumes ONTAP, è necessario scegliere una dimensione iniziale del disco. Dopodiché, puoi lasciare che BlueXP gestisca la capacità di un sistema per te, ma se vuoi creare aggregati, tieni presente quanto segue:
+
--
* Tutti i dischi di un aggregato devono avere le stesse dimensioni.
* Determinare lo spazio necessario, tenendo in considerazione le performance.
* Le performance dei dischi persistenti si ridimensionano automaticamente in base alle dimensioni del disco e al numero di vCPU disponibili per il sistema.
+
Per ulteriori informazioni, fare riferimento a quanto segue:

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Documentazione di Google Cloud: Dischi persistenti zonali (Standard e SSD)"^]
** https://cloud.google.com/compute/docs/disks/performance["Documentazione di Google Cloud: Ottimizzazione delle performance di dischi persistenti e SSD locali"^]




--




== Visualizzare i dischi di sistema predefiniti

Oltre allo storage per i dati degli utenti, BlueXP acquista anche lo storage cloud per i dati del sistema Cloud Volumes ONTAP (dati di avvio, dati root, dati core e NVRAM). A scopo di pianificazione, potrebbe essere utile esaminare questi dettagli prima di implementare Cloud Volumes ONTAP.

* link:reference-default-configs.html#google-cloud-single-node["Visualizzare i dischi predefiniti per i dati di sistema di Cloud Volumes ONTAP in Google Cloud"].
* https://cloud.google.com/compute/quotas["Documenti di Google Cloud: Quote delle risorse"^]
+
Il motore di calcolo per il cloud di Google applica quote sull'utilizzo delle risorse, in modo da garantire che non sia stato raggiunto il limite prima di implementare Cloud Volumes ONTAP.




TIP: Il connettore richiede anche un disco di sistema. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["Visualizza i dettagli sulla configurazione predefinita del connettore"^].



== Raccogliere informazioni di rete

Quando si implementa Cloud Volumes ONTAP in GCP, è necessario specificare i dettagli della rete virtuale. È possibile utilizzare un foglio di lavoro per raccogliere le informazioni dall'amministratore.

*Informazioni di rete per un sistema a nodo singolo*

[cols="30,70"]
|===
| Informazioni GCP | Il tuo valore 


| Regione |  


| Zona |  


| Rete VPC |  


| Subnet |  


| Policy firewall (se si utilizza il proprio) |  
|===
*Informazioni di rete per una coppia ha in più zone*

[cols="30,70"]
|===
| Informazioni GCP | Il tuo valore 


| Regione |  


| Zona per nodo 1 |  


| Zona per il nodo 2 |  


| Zona per il mediatore |  


| VPC-0 e subnet |  


| VPC-1 e subnet |  


| VPC-2 e subnet |  


| VPC-3 e subnet |  


| Policy firewall (se si utilizza il proprio) |  
|===
*Informazioni di rete per una coppia ha in una singola zona*

[cols="30,70"]
|===
| Informazioni GCP | Il tuo valore 


| Regione |  


| Zona |  


| VPC-0 e subnet |  


| VPC-1 e subnet |  


| VPC-2 e subnet |  


| VPC-3 e subnet |  


| Policy firewall (se si utilizza il proprio) |  
|===


== Scegliere una velocità di scrittura

BlueXP consente di scegliere un'impostazione della velocità di scrittura per Cloud Volumes ONTAP, ad eccezione delle coppie ad alta disponibilità (ha) in Google Cloud. Prima di scegliere una velocità di scrittura, è necessario comprendere le differenze tra le impostazioni normali e alte e i rischi e le raccomandazioni quando si utilizza un'elevata velocità di scrittura. link:concept-write-speed.html["Scopri di più sulla velocità di scrittura"].



== Scegliere un profilo di utilizzo del volume

ONTAP include diverse funzionalità di efficienza dello storage che consentono di ridurre la quantità totale di storage necessaria. Quando si crea un volume in BlueXP, è possibile scegliere un profilo che attiva queste funzionalità o un profilo che le disattiva. Dovresti saperne di più su queste funzionalità per aiutarti a decidere quale profilo utilizzare.

Le funzionalità di efficienza dello storage NetApp offrono i seguenti vantaggi:

Thin provisioning:: Presenta uno storage logico maggiore per gli host o gli utenti rispetto al pool di storage fisico. Invece di preallocare lo spazio di storage, lo spazio di storage viene allocato dinamicamente a ciascun volume durante la scrittura dei dati.
Deduplica:: Migliora l'efficienza individuando blocchi di dati identici e sostituendoli con riferimenti a un singolo blocco condiviso. Questa tecnica riduce i requisiti di capacità dello storage eliminando blocchi di dati ridondanti che risiedono nello stesso volume.
Compressione:: Riduce la capacità fisica richiesta per memorizzare i dati comprimendo i dati all'interno di un volume su storage primario, secondario e di archivio.

