---
sidebar: sidebar 
permalink: task-setting-up-gcp-encryption.html 
keywords: encryption, gcp, encryption key, permissions, customer-managed, gcpencryption 
summary: Mentre Google Cloud Storage crittografa sempre i tuoi dati prima che vengano scritti su disco, puoi utilizzare le API BlueXP per creare un sistema Cloud Volumes ONTAP che utilizza chiavi di crittografia gestite dal cliente. Si tratta di chiavi che vengono generate e gestite in GCP utilizzando il Cloud Key Management Service. 
---
= Utilizzo di chiavi di crittografia gestite dal cliente con Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mentre Google Cloud Storage crittografa sempre i tuoi dati prima che vengano scritti su disco, puoi utilizzare l'API BlueXP per creare un sistema Cloud Volumes ONTAP che utilizza _chiavi di crittografia gestite dal cliente_. Si tratta di chiavi che vengono generate e gestite in GCP utilizzando il Cloud Key Management Service.

.Fasi
. Assicurarsi che l'account di servizio di BlueXP Connector disponga delle autorizzazioni corrette a livello di progetto, nel progetto in cui è memorizzata la chiave.
+
Le autorizzazioni sono fornite in https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["Per impostazione predefinita, le autorizzazioni dell'account di servizio del connettore"^], Ma potrebbe non essere applicato se si utilizza un progetto alternativo per il Cloud Key Management Service.

+
Le autorizzazioni sono le seguenti:

+
[source, yaml]
----
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
----
. Assicurarsi che l'account di servizio per https://cloud.google.com/iam/docs/service-agents["Agente di servizio di Google Compute Engine"^] Dispone delle autorizzazioni Cloud KMS Encrypter/Decrypter sulla chiave.
+
Il nome dell'account del servizio utilizza il seguente formato: "Servizio-[numero_progetto_servizio]@compute-system.iam.gserviceaccount.com".

+
https://cloud.google.com/kms/docs/iam#granting_roles_on_a_resource["Documentazione Google Cloud: Utilizzo di IAM con Cloud KMS - assegnazione di ruoli a una risorsa"]

. Ottenere l'id della chiave richiamando il comando get per `/gcp/vsa/metadata/gcp-encryption-keys` Chiamata API o selezionando "Copy Resource Name" (Copia nome risorsa) sulla chiave nella console GCP.
. Se si utilizzano chiavi di crittografia gestite dal cliente e tiering dei dati per lo storage a oggetti, BlueXP tenta di utilizzare le stesse chiavi utilizzate per crittografare i dischi persistenti. Tuttavia, prima di tutto, dovrai abilitare i bucket di storage Google Cloud per utilizzare le chiavi:
+
.. Individuare l'agente del servizio Google Cloud Storage seguendo la https://cloud.google.com/storage/docs/getting-service-agent["Documentazione Google Cloud: Ottenere l'agente del servizio Cloud Storage"^].
.. Accedere alla chiave di crittografia e assegnare all'agente del servizio Google Cloud Storage le autorizzazioni di crittografia/decrypter Cloud KMS.


+
Per ulteriori informazioni, fare riferimento a. https://cloud.google.com/storage/docs/encryption/using-customer-managed-keys["Documentazione Google Cloud: Utilizzo di chiavi di crittografia gestite dal cliente"^]

. Utilizzare il parametro "GcpEncryption" con la richiesta API durante la creazione di un ambiente di lavoro.
+
*Esempio*

+
[source, json]
----
"gcpEncryptionParameters": {
    "key": "projects/project-1/locations/us-east4/keyRings/keyring-1/cryptoKeys/generatedkey1"
  }
----


Fare riferimento a. https://docs.netapp.com/us-en/bluexp-automation/index.html["Documenti sull'automazione BlueXP"^] Per ulteriori informazioni sull'utilizzo del parametro "GcpEncryption".
