---
sidebar: sidebar 
permalink: task-aws-key-management.html 
keywords: aws, amazon, encryption, NVE, NetApp volume encryption, KMIP, kms, key manager service 
summary: Utilizza il servizio di gestione delle chiavi di AWS per il tuo servizio di gestione delle chiavi di terze parti. 
---
= Gestione delle chiavi con AWS Key Management Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare link:https://docs.aws.amazon.com/kms/latest/developerguide/overview.html["KMS (Key Management Service) di AWS"^] Per proteggere le chiavi di crittografia ONTAP in un'applicazione implementata dalla piattaforma cloud Google.

La gestione delle chiavi con AWS KMS può essere abilitata con l'interfaccia CLI o l'API REST ONTAP.

Quando si utilizza il KMS, tenere presente che per impostazione predefinita viene utilizzata la LIF di un SVM di dati per comunicare con l'endpoint di gestione delle chiavi del cloud. Una rete di gestione dei nodi viene utilizzata per comunicare con i servizi di autenticazione di AWS. Se la rete del cluster non è configurata correttamente, il cluster non utilizzerà correttamente il servizio di gestione delle chiavi.

.Prima di iniziare
* Cloud Volumes ONTAP deve eseguire la versione 9.12.0 o successiva
* È necessario aver installato la licenza Volume Encryption (VE) e.
* È necessario aver installato la licenza MTEKM (Multi-tenant Encryption Key Management).
* Devi essere un amministratore del cluster o di SVM
* È necessario disporre di un abbonamento AWS attivo



NOTE: È possibile configurare le chiavi solo per una SVM dati.



== Configurazione

.AWS
. È necessario creare un link:https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#grant["concedi"^] Per la chiave AWS KMS che verrà utilizzata dal ruolo IAM che gestisce la crittografia. Il ruolo IAM deve includere una policy che consenta le seguenti operazioni:
+
** `DescribeKey`
** `Encrypt`
** `Decrypt`
Per creare una sovvenzione, fare riferimento a. link:https://docs.aws.amazon.com/kms/latest/developerguide/create-grant-overview.html["Documentazione AWS"^].


. link:https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html["Aggiungere un criterio al ruolo IAM appropriato."^] La policy dovrebbe supportare `DescribeKey`, `Encrypt`, e. `Decrypt` operazioni.


.Cloud Volumes ONTAP
. Passa all'ambiente Cloud Volumes ONTAP.
. Passare al livello di privilegio avanzato:
`set -privilege advanced`
. Abilitare il gestore delle chiavi AWS:
`security key-manager external aws enable -vserver _data_svm_name_ -region _AWS_region_ -key-id _key_ID_ -encryption-context _encryption_context_`
. Quando richiesto, inserire la chiave segreta.
. Verificare che AWS KMS sia stato configurato correttamente:
`security key-manager external aws show -vserver _svm_name_`

