---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: AutoSupport monitora in modo proattivo lo stato di salute del sistema e invia messaggi al supporto tecnico NetApp. Per impostazione predefinita, AutoSupport è attivato su ciascun nodo per inviare messaggi al supporto tecnico utilizzando il protocollo di trasporto HTTPS. Si consiglia di verificare che AutoSupport possa inviare questi messaggi. 
---
= Verificare l'installazione di AutoSupport
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport monitora in modo proattivo lo stato di salute del sistema e invia messaggi al supporto tecnico NetApp. Per impostazione predefinita, AutoSupport è attivato su ciascun nodo per inviare messaggi al supporto tecnico utilizzando il protocollo di trasporto HTTPS. Si consiglia di verificare che AutoSupport possa inviare questi messaggi.

L'unica fase di configurazione necessaria è garantire che Cloud Volumes ONTAP disponga di connettività Internet in uscita. Per ulteriori informazioni, consulta i requisiti di rete per il tuo cloud provider.



== Requisiti AutoSupport

I nodi Cloud Volumes ONTAP richiedono l'accesso a Internet in uscita per NetApp AutoSupport, che monitora in modo proattivo lo stato di salute del sistema e invia messaggi al supporto tecnico NetApp.

I criteri di routing e firewall devono consentire il traffico HTTP/HTTPS ai seguenti endpoint in modo che Cloud Volumes ONTAP possa inviare messaggi AutoSupport:

* \https://support.netapp.com/aods/asupmessage
* \https://support.netapp.com/asupprod/post/1.0/postAsup


Se non è disponibile una connessione Internet in uscita per l'invio di messaggi AutoSupport, BlueXP configura automaticamente i sistemi Cloud Volumes ONTAP in modo che utilizzino il connettore come server proxy. L'unico requisito è garantire che il gruppo di sicurezza del connettore consenta connessioni _inbound_ sulla porta 3128. Dopo aver implementato il connettore, aprire questa porta.

Se sono state definite rigide regole in uscita per Cloud Volumes ONTAP, è necessario anche assicurarsi che il gruppo di sicurezza Cloud Volumes ONTAP consenta connessioni _in uscita_ sulla porta 3128.

Dopo aver verificato che l'accesso a Internet in uscita è disponibile, è possibile testare AutoSupport per assicurarsi che sia in grado di inviare messaggi. Per istruzioni, fare riferimento a. https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["Documenti ONTAP: Configurazione di AutoSupport"^].



== Risolvere i problemi della configurazione AutoSupport

Se non è disponibile una connessione in uscita e BlueXP non è in grado di configurare il sistema Cloud Volumes ONTAP in modo che utilizzi il connettore come server proxy, verrà inviata una notifica da BlueXP intitolata "<working environment name> is unable to send AutoSupport messages" (Impossibile inviare messaggi Microsoft).

Molto probabilmente ricevi questo messaggio a causa di problemi di rete.

Per risolvere il problema, procedere come segue.

.Fasi
. SSH al sistema Cloud Volumes ONTAP in modo da poter amministrare il sistema dalla CLI.
+
link:task-connecting-to-otc.html["Scopri come passare da SSH a Cloud Volumes ONTAP"].

. Visualizzare lo stato dettagliato del sottosistema AutoSupport:
+
`autosupport check show-details`

+
La risposta deve essere simile a quanto segue:

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
Se lo stato della categoria http-https è "ok" significa che AutoSupport è configurato correttamente e che è possibile inviare messaggi.

. Se lo stato non è corretto, verificare l'URL del proxy per ciascun nodo Cloud Volumes ONTAP:
+
`autosupport show -fields proxy-url`

. Se il parametro dell'URL del proxy è vuoto, configurare Cloud Volumes ONTAP in modo che utilizzi il connettore come proxy:
+
`autosupport modify -proxy-url \http://<connector private ip>:3128`

. Verificare nuovamente lo stato AutoSupport:
+
`autosupport check show-details`

. Se lo stato continua a non essere corretto, verificare la presenza di connettività tra Cloud Volumes ONTAP e il connettore sulla porta 3128.
. Se l'ID di stato continua a non riuscire dopo aver verificato la presenza di connettività, SSH al connettore.
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html#connect-to-the-linux-vm["Scopri di più sulla connessione a Linux VM per il connettore"^]

. Passare a. `/opt/application/netapp/cloudmanager/docker_occm/data/`
. Aprire il file di configurazione del proxy `squid.conf`
+
La struttura di base del file è la seguente:

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
+
Il valore src di localnet è il CIDR del sistema Cloud Volumes ONTAP.

. Se il blocco CIDR del sistema Cloud Volumes ONTAP non rientra nell'intervallo specificato nel file, aggiornare il valore o aggiungere una nuova voce come segue:
+
`acl cvonet src <cidr>`

+
Se Aggiungi questa nuova voce, non dimenticare di aggiungere anche una voce Consenti:

+
`http_access allow cvonet`

+
Ecco un esempio:

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl cvonet src 172.33.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access allow cvonet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
. Dopo aver modificato il file di configurazione, riavviare il container proxy come sudo:
+
`docker restart squid`

. Tornare all'interfaccia utente di Cloud Volumes ONTAP e verificare che Cloud Volumes ONTAP possa inviare messaggi AutoSupport:
+
`autosupport check show-details`


