---
sidebar: sidebar 
permalink: task-google-key-manager.html 
keywords: google cloud, encryption, NVE, NetApp volume encryption, KMIP, GCP, GCP KMS, key manager service, encryption 
summary: Utilizza il servizio di gestione delle chiavi di Google per il servizio di gestione delle chiavi di terze parti. 
---
= Gestisci le chiavi con il Cloud Key Management Service di Google
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare link:https://cloud.google.com/kms/docs["Servizio di gestione delle chiavi di Google Cloud Platform (Cloud KMS)"^] Per proteggere le chiavi di crittografia ONTAP in un'applicazione implementata dalla piattaforma cloud Google.

La gestione delle chiavi con Cloud KMS può essere abilitata con la CLI o l'API REST di ONTAP.

Quando si utilizza Cloud KMS, tenere presente che per impostazione predefinita viene utilizzata la LIF di un SVM di dati per comunicare con l'endpoint di gestione delle chiavi del cloud. Una rete di gestione dei nodi viene utilizzata per comunicare con i servizi di autenticazione del provider cloud (oauth2.googleapis.com). Se la rete del cluster non è configurata correttamente, il cluster non utilizzerà correttamente il servizio di gestione delle chiavi.

.Prima di iniziare
* Cloud Volumes ONTAP deve eseguire la versione 9.10.1 o successiva
* Licenza VE (Volume Encryption) installata
* Licenza di gestione delle chiavi di crittografia multi-tenant (MTEKM) installata, a partire da Cloud Volumes ONTAP 9.12.1 GA.
* Devi essere un amministratore del cluster o di SVM
* Un abbonamento attivo a Google Cloud Platform


.Limitazioni
* Cloud KMS può essere configurato solo su una SVM dati




== Configurazione

.Google Cloud
. Nel tuo ambiente Google Cloud, link:https://cloud.google.com/kms/docs/creating-keys["Creare un anello e una chiave GCP simmetrici"^].
. Creare un ruolo personalizzato per l'account del servizio Cloud Volumes ONTAP.
+
[listing]
----
gcloud iam roles create kmsCustomRole
    --project=<project_id>
    --title=<kms_custom_role_name>
    --description=<custom_role_description>
    --permissions=cloudkms.cryptoKeyVersions.get,cloudkms.cryptoKeyVersions.list,cloudkms.cryptoKeyVersions.useToDecrypt,cloudkms.cryptoKeyVersions.useToEncrypt,cloudkms.cryptoKeys.get,cloudkms.keyRings.get,cloudkms.locations.get,cloudkms.locations.list,resourcemanager.projects.get
    --stage=GA
----
. Assegnare il ruolo personalizzato alla chiave KMS cloud e all'account del servizio Cloud Volumes ONTAP:
`gcloud kms keys add-iam-policy-binding _key_name_ --keyring _key_ring_name_ --location _key_location_ --member serviceAccount:_service_account_Name_ --role projects/_customer_project_id_/roles/kmsCustomRole`
. Scarica la chiave JSON dell'account di servizio:
`gcloud iam service-accounts keys create key-file --iam-account=_sa-name_@_project-id_.iam.gserviceaccount.com`


.Cloud Volumes ONTAP
. Connettersi alla LIF di gestione del cluster con il client SSH preferito.
. Passare al livello di privilegio avanzato:
`set -privilege advanced`
. Creare un DNS per i dati SVM.
`dns create -domains c._<project>_.internal -name-servers _server_address_ -vserver _SVM_name_`
. Crea voce CMEK:
`security key-manager external gcp enable -vserver _SVM_name_ -project-id _project_ -key-ring-name _key_ring_name_ -key-ring-location _key_ring_location_ -key-name _key_name_`
. Quando richiesto, inserire la chiave JSON dell'account di servizio dal proprio account GCP.
. Confermare che il processo di abilitazione è riuscito:
`security key-manager external gcp check -vserver _svm_name_`
. FACOLTATIVO: Creare un volume per verificare la crittografia `vol create _volume_name_ -aggregate _aggregate_ -vserver _vserver_name_ -size 10G`




== Risolvere i problemi

Se è necessario risolvere il problema, è possibile eseguire il tail dei log REST API raw nei due passaggi precedenti:

. `set d`
. `systemshell -node _node_ -command tail -f /mroot/etc/log/mlog/kmip2_client.log`

